"""Add preferred_language to users

Revision ID: 2261f25e402e
Revises: 8386951938fb
Create Date: 2025-06-18 11:31:49.188335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2261f25e402e'
down_revision = '8386951938fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), nullable=True))
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
