"""Fix: added timestamps and admin flag

Revision ID: 2f70c940b308
Revises: c92ff90a01a4
Create Date: 2025-06-18 09:21:57.571130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f70c940b308'
down_revision = 'c92ff90a01a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('recipe_title', sa.String(length=255), nullable=True))
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('meal_plan_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('plan_date')

    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('api_source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=False)
        batch_op.alter_column('api_source',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_date', sa.DATE(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('meal_plan_ibfk_2'), 'recipes', ['recipe_id'], ['id'])
        batch_op.alter_column('recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('recipe_title')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
